name: floaty_chathead
description: A Flutter plugin for floating chathead bubbles with Flutter widget content panels.
version: 3.0.0
homepage: https://github.com/Crdzbird/floaty_chathead

environment:
  sdk: '>=3.0.0 <5.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^22.7.2

flutter:
  plugin:
    platforms:
      android:
        package: ni.devotion.floaty_head
        pluginClass: FloatyHeadPlugin
