name: floaty_head
description: A flutter plugin to create custom chatheads with hidden content displayed on tap, like Messenger.
author: Luis Cardoza Bird <luisalfonsocb83@gmail.com>
version: 2.0.0-nullsafety.0
homepage: https://github.com/Crdzbird/floaty_chathead

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ni.devotion.floaty_head
        pluginClass: FloatyHeadPlugin
      ios:
        pluginClass: FloatyHeadPlugin